### ISSUE TITLE
Build first version of basic utility measure

### ISSUE THREAD

**Issue by yoid2000** [gda-score/anon-utility#1]
The GDA Score has both a defense and a utility component. The defense component is in the attacks repo. This repo will contain software for measuring utility. I have in mind the ability to produce a diagram something like this:

![dpbar1](https://user-images.githubusercontent.com/2162345/45673265-8473c400-bb2a-11e8-9abe-26c16dee131e.PNG)

Where on the left side the utility is conveyed. Details of this diagram are likely to change, but this is the basic idea.

From this diagram, you can see that we want three values, the `accuracy` (Ac), the `coverage` (Cv), and a composite of the two (`utility`). 

The basic approach to the utility measure is to make a set of queries against the raw and anonymized databases, and compare the answers. Coverage suffers when the anonymized database cannot return an answer at all. Accuracy suffers when the answer is less accurate. For utility to be good, both coverage and accuracy must be good.

I envision multiple accuracy measures, encompassing everything from simple counts to ML techniques, but let's start simple.

The module will use `askExplore()` and `getExplore()` from class `gdaAttack()` in `library/gdaScore.py` to generate the queries and supply the answers. An example of this usage can be found in `examples/explore1.py`. Note we can also use the `gdaAttack()` helper functions `getTableNames()` and `getColNamesAndTypes()`. (As of this writing these need to be updated to include DB selection.)

Coverage will be measured as the fraction of queries that could be made on the raw db that returned nothing from the anon db. For accuracy we'll need to play around, but I'm supposing that it will be a mean square error measure of at least:
1. absolute error (`raw_value - anon_value`), 
2. simple relative error (`raw_value / anon_value`), and
3. relative error measured as `abs(anon_value - raw_value) / max(anon_value, raw_value)`

Write a class that does the following:

* Get tables and columns from both raw and anon DBs.
* Check and see if there are any columns in raw that are not included in anon. For each such column, we'll deduct from the coverage score (in essence, the queries that could be made to the raw columns cannot be made to the anon columns)
* For each column for both DBs, generate a histogram as follows:

```
SELECT column, count(distinct uid)
FROM table
GROUP BY 1
```

* Count the number of raw DB answer rows with value 1. We won't include these in the score because no anonymization algorithm can be expected to return values that pertain to a single user (this would break privacy).
* For those raw answer rows with count greater than 1, count the number of rows included in the raw answer but not included in the anon answer. This count will deduct from the coverage score.
* For those rows that are included in both answers, measure the absolute and relative error as described above.

* Do the same for every pair of columns:

```
SELECT column1, column2, count(distinct uid)
FROM table
GROUP BY 1,2
```

* Compute coverage and mean square error

**Comment by yoid2000** [comment]
@srnb 

I had a look at your results file, but not sure how to read it. Could you give me a brief description of what I should be looking at? Also, in future, could you pretty-print those?

**Comment by srnb** [comment]
There are two parts, the accuracy and coverage calculated for every column and multicolumn(every pair) as mentioned above. Coverage is a single value mentioned in the file and there are two dictionaries that are printed has column-wise accuracy calculated for both every column and also for the pair of columns.

**Comment by yoid2000** [comment]
Ok, this is a good first cut.

Some requests:

1. Arrange your output so that the entire results are in a single json file.  (So for instance the first character will be `{`.) See example from the attacks in the next comment. Don't worry if the json file is pretty big.
2. Each output should be for one table. In fact, the program should be arranged in such a way that it runs only for one table.
3. Arrange the program operation so that it reads in the parameters from a json file (rather than embedding them in the code, i.e. line 221). For an example of this, you can see gda-score/attacks. There is for instance the attack `dumbList_SingOut.py` which has a corresponding config file `dumbList_SingOut.py.json`. The params are read in with `setupGdaAttackParameters()`, and a separate attack is run for each item in the config file (for which there are two here). So in your case, you'd have one utility measure per table, so your config file would have seven separate utility configs.
4. For reporting coverage, please report more information, for instance for each column and column pair:
  - How many values with count 1 from the raw table
  - How many values with count >1 from the raw table
  - How many values returned from the anonymized table
  - How many of the values from anonymized table have a match in the raw table
  - The per-column coverage (item 4 / item 2)
5. For each column pair, list the column names, not the column positions
6. In the output, please add all of the input parameters. The contents of the json file should tell us everything about which utility measure was run (including the type of utility measure, which in this case is comparing distinct UID counts for distinct column values)
7. Your current output gives "Mean Absolute Error Per Column" twice. I guess one of these should be relative error (looking at the numbers, I guess the first one)?
8. For each json file, please also include the operational results returned by the call `getOpParameters` (see https://gda-score.github.io/gdaScore.m.html for pretty documentation)
9. In the json file, please group all of per-column information together. In other words, for a given column 'foo', I'd like to see both the coverage data and accuracy data together.
10. You are missing the third error measure (relative error measured as `abs(anon_value - raw_value) / max(anon_value, raw_value)`)
11. In addition to mean squared error for each error measure, please report max error, min error, avg error, and error standard deviation.
12. We'll be doing a bunch more utility measures, so please think about what parts of your code would serve as general utility functions, and therefore can be implements as a separate class in a separate file.

Also, for now you should run these without removing the cache file. That way, when you make subsequent runs after making changes, it'll go much faster. (to do this, set `cleanUpCache=False` in the `cleanUp()` call). Note this not fully debugged, so may not actually work as promised.

**Comment by yoid2000** [comment]
Here is the type of output I produce for one attack:

```
{
    "finished": true,
    "params": {
        "anonDb": "cloakBanking",
        "anonSubType": "",
        "anonType": "anon_diffix",
        "criteria": "inference",
        "dbType": "banking",
        "flushCache": false,
        "name": "diffix_infer_1.py.anon_diffix.banking.accounts",
        "rawDb": "gdaScoreBankingRaw",
        "resultsDir": "",
        "resultsPath": "attackResults/diffix_infer_1.py.anon_diffix.banking.accounts.json",
        "table": "accounts",
        "uid": "client_id",
        "verbose": false
    },
    "score": {
        "attack": {
            "anonDb": "cloakBanking",
            "anonDbName": "gda_banking",
            "anonHost": "attack.aircloak.com",
            "anonPort": 8432,
            "attackName": "diffix_infer_1.py.anon_diffix.banking.accounts",
            "criteria": "inference",
            "rawDb": "gdaScoreBankingRaw",
            "rawDbName": "banking",
            "rawHost": "db001.gda-score.org",
            "rawPort": 5432,
            "startTime": "2018-10-02 16:41:01.381232",
            "table": "accounts"
        },
        "base": {
            "attackCells": 1293,
            "attackGets": 13,
            "knowledgeCells": 0,
            "knowledgeGets": 0
        },
        "col": {
            "account_id": {
                "avgConfidenceRatios": 0,
                "claimCorrect": 0,
                "claimError": 0,
                "claimMade": 0,
                "claimPassCorrect": 0,
                "claimTrials": 0,
                "columnSusceptibility": 1.0,
                "numConfidenceRatios": 0,
                "sumConfidenceRatios": 0
            },
            "acct_date": {
                "avgConfidenceRatios": 0,
                "claimCorrect": 0,
                "claimError": 0,
                "claimMade": 0,
                "claimPassCorrect": 0,
                "claimTrials": 0,
                "columnSusceptibility": 1.0,
                "numConfidenceRatios": 0,
                "sumConfidenceRatios": 0
            },
            "acct_district_id": {
                "avgConfidenceRatios": 0,
                "claimCorrect": 0,
                "claimError": 0,
                "claimMade": 0,
                "claimPassCorrect": 0,
                "claimTrials": 0,
                "columnSusceptibility": 1.0,
                "numConfidenceRatios": 0,
                "sumConfidenceRatios": 0
            },
            "birth_number": {
                "avgConfidenceRatios": 0,
                "claimCorrect": 0,
                "claimError": 0,
                "claimMade": 0,
                "claimPassCorrect": 0,
                "claimTrials": 0,
                "columnSusceptibility": 1.0,
                "numConfidenceRatios": 0,
                "sumConfidenceRatios": 0
            },
            "cli_district_id": {
                "avgConfidenceRatios": 0,
                "claimCorrect": 0,
                "claimError": 0,
                "claimMade": 0,
                "claimPassCorrect": 0,
                "claimTrials": 0,
                "columnSusceptibility": 1.0,
                "numConfidenceRatios": 0,
                "sumConfidenceRatios": 0
            },
            "client_id": {
                "avgConfidenceRatios": 0,
                "claimCorrect": 0,
                "claimError": 0,
                "claimMade": 0,
                "claimPassCorrect": 0,
                "claimTrials": 0,
                "columnSusceptibility": 1.0,
                "numConfidenceRatios": 0,
                "sumConfidenceRatios": 0
            },
            "disp_type": {
                "avgConfidenceRatios": 0.8325557339424845,
                "claimCorrect": 62,
                "claimError": 0,
                "claimMade": 121,
                "claimPassCorrect": 0,
                "claimProbability": 1.0,
                "claimTrials": 121,
                "columnSusceptibility": 1.0,
                "confidence": 0.512396694214876,
                "confidenceImprovement": -1.912033462033492,
                "defense": 1,
                "numConfidenceRatios": 121,
                "sumConfidenceRatios": 100.73924380704062
            },
            "frequency": {
                "avgConfidenceRatios": 0.9275470292419437,
                "claimCorrect": 0,
                "claimError": 0,
                "claimMade": 41,
                "claimPassCorrect": 0,
                "claimProbability": 1.0,
                "claimTrials": 41,
                "columnSusceptibility": 1.0,
                "confidence": 0.0,
                "confidenceImprovement": -12.802056555269763,
                "defense": 1,
                "numConfidenceRatios": 41,
                "sumConfidenceRatios": 38.02942819891969
            },
            "lastname": {
                "avgConfidenceRatios": 0,
                "claimCorrect": 0,
                "claimError": 0,
                "claimMade": 0,
                "claimPassCorrect": 0,
                "claimTrials": 0,
                "columnSusceptibility": 1.0,
                "numConfidenceRatios": 0,
                "sumConfidenceRatios": 0
            }
        },
        "operational": {
            "avCacheGetDuration": 0.00024911322645292485,
            "avCachePutDuration": 0.021849499999999855,
            "avQueryDuration": 0.007353683231083855,
            "numCacheGets": 499,
            "numCachePuts": 2,
            "numQueries": 498,
            "timeCacheGets": 0.12430750000000951,
            "timeCachePuts": 0.04369899999999971,
            "timeQueries": 3.876300300000004
        },
        "scores": {
            "claimProbability": 1.0,
            "columnsUsed": [
                "frequency",
                "disp_type"
            ],
            "confidenceImprovement": -7.357045008651627,
            "defense": 1.0,
            "knowledgeNeeded": 0.0,
            "susceptibility": 0.2222222222222222,
            "workNeeded": 7.981481481481482
        },
        "tableStats": {
            "colNamesAndTypes": [
                [
                    "account_id",
                    "integer"
                ],
                [
                    "acct_district_id",
                    "integer"
                ],
                [
                    "frequency",
                    "text"
                ],
                [
                    "acct_date",
                    "integer"
                ],
                [
                    "client_id",
                    "integer"
                ],
                [
                    "disp_type",
                    "text"
                ],
                [
                    "birth_number",
                    "text"
                ],
                [
                    "cli_district_id",
                    "integer"
                ],
                [
                    "lastname",
                    "text"
                ]
            ],
            "numColumns": 9,
            "totalRows": 5369
        }
    }
}
```

**Comment by srnb** [comment]
Please find the suggested format for the output: Please let me know if there are any modifications needed:
The output is generated per table basis and stored as separate files. The score has sub-elements for each column and pair of columns and they, in turn, contain subelements such as coverage and accuracy metrics.

Output Per Table:
{
  "finished": true,
  "params": {
    "anonDb": "cloakBankingAnon",
    "anonSubType": "",
    "anonType": "",
    "criteria": "singlingOut",
    "dbType": "",
    "flushCache": false,
    "name": "accountsTableUtilityMeasure",
    "rawDb": "gdaScoreBankingRaw",
    "resultsDir": "/anon-utility/results",
    "resultsPath": "/anon-utility/results/accountsTableUtilityMeasure.json",
    "table": "accounts",
    "uid": "client_id",
    "verbose": false
  },
  "score": {
    "account_id": {
      "accuracy": {
        "absolErrorMetrics": {
          "absolError": 0.0,
          "avg": 0,
          "max": 0,
          "min": 0,
          "stddev": 0.0
        },
        "relativeErrorMetrics": {
          "avg": 0.0,
          "max": 0.0,
          "min": 0.0,
          "simpleRelativeError": 0.0,
          "stddev": 0.0
        },
        "simpleRelativeErrorMetrics": {
          "avg": 1.0,
          "max": 1.0,
          "min": 1.0,
          "simpleRelativeError": 1.0,
          "stddev": 0.0
        }
      },
      "coverage": {
        "colCountManyRawDb": 869,
        "colCountOneRawDb": 3631,
        "coveragePerCol": 0.010356731875719217,
        "totalValCntAnonDb": 5368,
        "valuesInBothRawAndAnonDb": 9
      }
    },
    "account_id:acct_district_id": {
      "accuracy": {
        "absolErrorMetrics": {
          "absolError": 0.0,
          "avg": 0,
          "max": 0,
          "min": 0,
          "stddev": 0.0
        },
        "relativeErrorMetrics": {
          "avg": 0.0,
          "max": 0.0,
          "min": 0.0,
          "simpleRelativeError": 0.0,
          "stddev": 0.0
        },
        "simpleRelativeErrorMetrics": {
          "avg": 1.0,
          "max": 1.0,
          "min": 1.0,
          "simpleRelativeError": 1.0,
          "stddev": 0.0
        }
      },
      "coverage": {
        "colCountManyRawDb": 869,
        "colCountOneRawDb": 3631,
        "coveragePerCol": 0.0667433831990794,
        "totalValCntAnonDb": 5368,
        "valuesInBothRawAndAnonDb": 58
      }
    }
  },
  "operational": {
    "avCacheGetDuration": 0,
    "avCachePutDuration": 0.0007633332463324462,
    "avQueryDuration": 0.7203481172405494,
    "numCacheGets": 0,
    "numCachePuts": 76,
    "numQueries": 90,
    "timeCacheGets": 0,
    "timeCachePuts": 0.05801332672126591,
    "timeQueries": 64.83133055164944
  },
  "tableStats": {
    "colNames": [
      "client_id",
      "frequency",
      "birth_number",
      "disp_type",
      "cli_district_id",
      "lastname",
      "acct_date",
      "account_id",
      "acct_district_id"
    ]
  }
}

**Comment by yoid2000** [comment]
Please make the column names a key rather than a value. The way you record accuracy and coverage is ok.

I suggest that instead of "score" you can have "singleColumnScores", which is an array:

```
"singleColumnScores": [
]
```

Then each entry in the array covers a single column. Like this:

```
"singleColumnScores": [
  { "col": "account_id",
    "accuracy": {.....},
    "coverage": {......}
  },
  { ......
  }
]
```

Then a separate entry for double column scores:


```
"doubleColumnScores": [
  { "col1": "account_id",
    "col2": "acct_district_id",
    "accuracy": {.....},
    "coverage": {......}
  },
  { ......
  }
]
```

something like that.

**Comment by srnb** [comment]
"totalValCntAnonDb" I was a mistake in code, adding up the whole column count. Now I have changed it.
Please find the update JSON format(Incomplete) and also I have sent the complete JSON file. Please let me know if any further changes are needed.
{
    "SingleColumnScores": [
        {
            "accuracy": {
                "absolErrorMetrics": {
                    "avg": 1.2207792207792207,
                    "compute": "meanSquare(count(distinct_rawDb)-count(distinct_anonDb))",
                    "max": 4,
                    "meanSquareError": 2.3636363636363638,
                    "min": 0,
                    "stddev": 0.9406517424717685
                },
                "relativeErrorMetrics": {
                    "avg": 0.021117997428110744,
                    "max": 0.0625,
                    "meanSquareError": 0.0007106859166670811,
                    "min": 0.0,
                    "stddev": 0.016376788692822383
                },
                "simpleRelativeErrorMetrics": {
                    "avg": 0.9974869069119172,
                    "compute": "meanSquare(abs(count(distinct_rawDb)-count(distinct_anonDb))/max(count(distinct_rawDb),count(distinct_anonDb)))",
                    "max": 1.0666666666666667,
                    "meanSquareError": 0.9957110775190382,
                    "min": 0.9387755102040817,
                    "stddev": 0.027213338566666388
                }
            },
            "col1": "acct_district_id",
            "coverage": {
                "colCountManyRawDb": 77,
                "colCountOneRawDb": 0,
                "coveragePerCol": 1.0,
                "totalValCntAnonDb": 77,
                "valuesInBothRawAndAnonDb": 77
            }
        }
    ],
    "doubleColumnScores": [
    {
      "accuracy": {
        "absolErrorMetrics": {
          "avg": 1.4615384615384615,
          "compute": "meanSquare(count(distinct_rawDb)-count(distinct_anonDb))",
          "max": 5,
          "meanSquareError": 3.5934065934065935,
          "min": 0,
          "stddev": 1.2138798431081528
        },
        "relativeErrorMetrics": {
          "avg": 0.054096741105169696,
          "max": 0.3333333333333333,
          "meanSquareError": 0.010517063654457126,
          "min": 0.0,
          "stddev": 0.08760677100413725
        },
        "simpleRelativeErrorMetrics": {
          "avg": 1.0425823060813317,
          "compute": "meanSquare(abs(count(distinct_rawDb)-count(distinct_anonDb))/max(count(distinct_rawDb),count(distinct_anonDb)))",
          "max": 1.5,
          "meanSquareError": 1.1069860656537733,
          "min": 0.9038461538461539,
          "stddev": 0.14223401154792575
        }
      },
      "col1": "acct_district_id",
      "col2": "cli_district_id",
      "coverage": {
        "colCountManyRawDb": 180,
        "colCountOneRawDb": 266,
        "coveragePerCol": 0.5055555555555555,
        "totalValCntAnonDb": 145,
        "valuesInBothRawAndAnonDb": 91
      }
    }
    ],
    "finished": true,
  "operational": {
    "avCacheGetDuration": 0,
    "avCachePutDuration": 0.0008259550086222589,
    "avQueryDuration": 0.7924200004212455,
    "numCacheGets": 0,
    "numCachePuts": 80,
    "numQueries": 90,
    "timeCacheGets": 0,
    "timeCachePuts": 0.06607640068978071,
    "timeQueries": 71.3178000379121
  },
  "params": {
    "anonDb": "cloakBankingAnon",
    "anonSubType": "",
    "anonType": "",
    "criteria": "singlingOut",
    "dbType": "",
    "flushCache": false,
    "name": "accountsTableUtilityMeasure",
    "rawDb": "gdaScoreBankingRaw",
    "resultsDir": "/home/sriharsha/PycharmProjects/anon-utility/results",
    "resultsPath": "/home/sriharsha/PycharmProjects/anon-utility/results/accountsTableUtilityMeasure.json",
    "table": "accounts",
    "uid": "client_id",
    "verbose": false
  },
  "tableStats": {
    "colNames": [
      "acct_district_id",
      "cli_district_id",
      "lastname",
      "client_id",
      "frequency",
      "birth_number",
      "disp_type",
      "account_id",
      "acct_date"
    ]
  }
}      

@question: If there are no matching records between anonDb and rawDb. For accuracy, I haven't included the corresponding tag in the  JSON output. Should we have to include the tag(with no other subelements or value as 'None' or something)?.
If "coveragePerCol"(colCountManyRawDb ==0) or standard deviation (For single value) in this condition values can't be computed. So,values their values are 'None'.

**Comment by srnb** [comment]
To write a output to JSON file, `finishGdaAttack` method under `gdaUtilities` by default adds "score" as key for input parameter (score). The same function can be reused in this scenario if we could add another parameter to a method to check whether to add or not the key(That's why score tag is added ). Or else if we don't want to modify the output would be like:
{ "score":{
   "singleColumnScore"[,,,],
    "doubleColumnScore"[,,,],
    "operational":{,,},
     "tableStats":{,,}
},
"params":{},
"finished": true
}

**Comment by yoid2000** [comment]
For the case where you can't compute accuracy, instead of using the string "None" for `coveragePerCol`, please use the python `None`, which I believe will result in the json constant `NULL`.

**Comment by yoid2000** [comment]
> @question: If there are no matching records between anonDb and rawDb. For accuracy, I haven't included the corresponding tag in the JSON output. Should we have to include the tag(with no other subelements or value as 'None' or something)?.

I'm ok with simply omitting it. (I'd have been ok with the alternative also)

> If "coveragePerCol"(colCountManyRawDb ==0) or standard deviation (For single value) in this condition values can't be computed. So,values their values are 'None'.

Ok. But again lets use the python constant `None` instead of the string "None".

**Comment by yoid2000** [comment]
> To write a output to JSON file, finishGdaAttack method under gdaUtilities by default adds "score" as key for input parameter (score). The same function can be reused in this scenario if we could add another parameter to a method to check whether to add or not the key(That's why score tag is added ). Or else if we don't want to modify the output would be like:

I'd rather not try to overload (reuse) `finishGdaAttack`. I'd rather have a separate function, maybe called `finishGdaUtility` or something like that.

The `score` item in the attack json is kinda ugly, so you don't need to replicate it.

**Comment by yoid2000** [comment]
I see you closed this. Where is the code?

**Comment by srnb** [comment]
I have raised a pull request already. But I have missed commenting on the pull request.

**Comment by yoid2000** [comment]
Ok I'll look. I'm not sure I'm being notified of pull requests

PF
